print("                              Resume              ")
print("")
print("")


fname=input(" ")
email=input("Email:")
address=input("Address:")
Mobile=input("Mobile No:")
print("")
print("")


print("       I want to succeed in an environment of growth and excellence to meet personal and organiztional goals.")
print("")
print("")

print("Educational Qualifications:")
print("")
print("")
print("    BOARD      "+"             YEAR        "+"            SCHOOL/COLLEGE")
print("")
print("Krishna Universty"+"           2018        "+"          Sri Bala Sai Degree College")
print("Intermediate      "+"          2015        "+"          Sri Chaithanya Jr.kalasala")
print("SSC      "+"                   2013        "+"          St.vincent Pallotti E.M")
print("")
print("")
print("")
print("Interests:")
print("           Crochet making")
print("           Playing games")
print("           Listening to music")
print("")
print("")
print("     I here by declare that all the above given information is true to the best of my Knowledge and belief.")
      
print("")
print("")
place=input("Place:")
print("")
date=input("Date:")
print("                                                                     A.H.D.Jyothi")
